#!/usr/bin/env python3
"""Generate the SDK constants from the single source of truth (client/order.py).

WHY THIS EXISTS — the one real danger of a TypeScript SDK is a SECOND SOURCE OF TRUTH:
retyping ORDER_TYPEHASH, the witness type string, or the Order field order in TS recreates
the Across M-06 failure class this project avoids everywhere else. A silent drift between
the TS constant and the Solidity/Python constant produces signatures that verify nowhere.

So: GENERATE, NEVER RETYPE. This script imports client/order.py (and the expiry defaults
from distribution/relay.py) and emits two artifacts:

    sdk/src/generated/constants.ts   (typed, `as const`)
    sdk/src/generated/constants.js   (plain ESM — index.html imports it with no build step)

Every hash-bearing value (typehashes, hashed name) is PRECOMPUTED here in Python — the TS
side never re-derives a hash it could get wrong. Output is DETERMINISTIC (no timestamps):
the SDK drift test regenerates into a temp dir and asserts byte equality with the committed
files, so any drift — or any hand edit — goes red.

Usage:
    python3 scripts/gen_constants.py [output_dir]     # default: sdk/src/generated
"""

from __future__ import annotations

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "client"))
sys.path.insert(0, os.path.join(ROOT, "distribution"))

from eth_hash.auto import keccak  # noqa: E402

import order as O  # noqa: E402  — THE single source
import relay as R  # noqa: E402  — expiry defaults only

ORDER_FIELDS = (
    "maker", "taker", "sellToken", "buyToken", "sellAmount", "buyAmount",
    "recipient", "maxTip", "fillWindow", "deadline",
)

HEADER = """\
// DO NOT EDIT — generated by scripts/gen_constants.py from client/order.py.
// client/order.py is the single source of truth for every value below; editing this
// file by hand recreates the M-06 second-source-of-truth failure class. The SDK drift
// test asserts byte equality between this file and a fresh regeneration.
"""


def _hex(b: bytes) -> str:
    return "0x" + b.hex()


def constants() -> list[tuple[str, str, str]]:
    """(name, ts_value_literal, doc) — value literals are valid in both TS and JS."""
    witness_typehash = keccak(
        O.PERMIT_WITNESS_TRANSFER_FROM_STUB.encode() + O.WITNESS_TYPE_STRING.encode()
    )
    return [
        ("PERMIT2", repr_js(O.PERMIT2),
         "Canonical Permit2 singleton (same address on every chain)."),
        ("ZERO_ADDRESS", repr_js("0x" + "00" * 20),
         "address(0) — an open order's taker."),
        ("ORDER_TYPE", repr_js(O.ORDER_TYPE),
         "EIP-712 Order type string. Field order is frozen; reordering kills every signature."),
        ("ORDER_TYPEHASH", repr_js(_hex(O.ORDER_TYPEHASH)),
         "keccak256(ORDER_TYPE)."),
        ("WITNESS_TYPE_STRING", repr_js(O.WITNESS_TYPE_STRING),
         "Byte-exact Permit2 witness type string (referenced structs alphabetical)."),
        ("PERMIT_WITNESS_TRANSFER_FROM_STUB", repr_js(O.PERMIT_WITNESS_TRANSFER_FROM_STUB),
         "Permit2's PermitHash stub, prepended to WITNESS_TYPE_STRING."),
        ("PERMIT_WITNESS_TYPEHASH", repr_js(_hex(witness_typehash)),
         "keccak256(STUB + WITNESS_TYPE_STRING) — the full PermitWitnessTransferFrom typehash."),
        ("TOKEN_PERMISSIONS_TYPEHASH", repr_js(_hex(O.TOKEN_PERMISSIONS_TYPEHASH)),
         'keccak256("TokenPermissions(address token,uint256 amount)").'),
        ("EIP712_DOMAIN_TYPEHASH", repr_js(_hex(O.EIP712_DOMAIN_TYPEHASH)),
         'keccak256("EIP712Domain(string name,uint256 chainId,address verifyingContract)").'),
        ("PERMIT2_HASHED_NAME", repr_js(_hex(O.PERMIT2_HASHED_NAME)),
         'keccak256("Permit2") — the Permit2 domain name hash.'),
        ("ORDER_FIELDS", "[" + ", ".join(repr_js(f) for f in ORDER_FIELDS) + "]",
         "The 10 Order fields, in frozen struct/typehash order."),
        ("QUOTE_TTL", str(R.QUOTE_TTL),
         "Seconds; deadline - now at quote issuance (L1 doubles it)."),
        ("HOT_WINDOW", str(R.HOT_WINDOW),
         "Seconds; fillWindow - now (maker-only before it)."),
    ]


def repr_js(s: str) -> str:
    # JSON-style double-quoted string, valid in both TS and JS.
    import json
    return json.dumps(s)


def render(ts: bool) -> str:
    lines = [HEADER]
    for name, value, doc in constants():
        lines.append(f"/** {doc} */")
        suffix = " as const" if ts else ""
        lines.append(f"export const {name} = {value}{suffix};")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    out_dir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "sdk", "src", "generated")
    os.makedirs(out_dir, exist_ok=True)
    for ext, ts in (("ts", True), ("js", False)):
        path = os.path.join(out_dir, f"constants.{ext}")
        with open(path, "w") as fh:
            fh.write(render(ts))
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
